object:
  akana_url_1: 'https://fssfed.ge.com/fss/as/token.oauth2?grant_type=client_credentials&client_id='
  client_id: '*******************************'
  akana_url_2: '&client_secret='
  client_secret: '*******************************'
  akana_url_3: '&scope=api'
  box_token_url_1: 'https://api.ge.com/digital/boxapi/v2/token?email='
  sso_email_id: 'service.boxapifunctionalsso@ge.com'
  box_url_1: 'https://api.box.com/2.0/folders/'
  folder_id: '39832155676'
  box_url_2: '/items?limit=100000&offset=0'
  proxy1: 'http://proxy-src.research.ge.com:8080'
  proxy2: 'https://proxy-src.research.ge.com:8080'
  upload_url: 'https://upload.box.com/api/2.0/files/content'
